#!/usr/bin/env python3
"""Bundle the material-osc Lua sources into one deployable script."""

from __future__ import annotations

import argparse
import re
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parent
DEFAULT_SOURCE_DIR = ROOT / "src"
ENTRY_FILE = DEFAULT_SOURCE_DIR / "main.lua"
FONTS_DIR = ROOT / "fonts"
BUILD_DIR = ROOT / "build"
ENTRY_MARKER = "-- ===== material-osc entry point ====="
GENERATED_HEADER = "-- Generated by bundle.py. Do not edit this file directly."
SYMBOL_FONT = "MaterialSymbolsRoundedUnfilled.ttf"
TEXT_FONT = "GoogleSansFlex.ttf"
OUTPUT_SYMBOL_FONT = "material-osc_icons.otf"
OUTPUT_TEXT_FONT = "material-osc_google_sans_flex.ttf"
LUA_STRING = re.compile(r'''["']([a-z][a-z0-9_]*(?:\.[a-z0-9_]+)?)["']''')
LUA_IDENTIFIER = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")
LUA_NUMBER = re.compile(
    r"""
    (?:
        0[xX](?:
            [0-9A-Fa-f]+(?:\.[0-9A-Fa-f]*)?
            |\.[0-9A-Fa-f]+
        )(?:[pP][+-]?[0-9]+)?
        |
        (?:
            [0-9]+\.[0-9]*
            |\.[0-9]+
            |[0-9]+
        )(?:[eE][+-]?[0-9]+)?
    )
    """,
    re.VERBOSE,
)
LUA_OPERATORS = ("...", "..", "==", "~=", "<=", ">=", "::", "//", "<<", ">>")
AMBIGUOUS_SYMBOL_BOUNDARIES = {
    "--", "..", "==", "~=", "<=", ">=", "::", "//", "<<", ">>", "[["
}


def module_name(path: Path, source_dir: Path) -> str:
    relative = path.relative_to(source_dir.parent).with_suffix("")
    return ".".join(relative.parts)


def read_entry_point(entry_file: Path) -> str:
    """Read the hand-written entry point."""
    if not entry_file.is_file():
        raise FileNotFoundError(
            f"Entry point not found: {entry_file}"
        )

    contents = entry_file.read_text(encoding="utf-8")
    if ENTRY_MARKER in contents:
        contents = contents.split(ENTRY_MARKER, 1)[1]
    return contents.lstrip("\r\n")


def build_bundle(source_dir: Path, entry_file: Path) -> tuple[str, int]:
    entry_point = read_entry_point(entry_file)
    lua_files = sorted(
        path for path in source_dir.rglob("*.lua") if path.resolve() != entry_file.resolve()
    )
    if not lua_files:
        raise FileNotFoundError(f"No Lua modules found under {source_dir}")

    sections = [GENERATED_HEADER, ""]
    for path in lua_files:
        name = module_name(path, source_dir)
        source = path.read_text(encoding="utf-8").rstrip()
        sections.extend(
            (
                f"-- ===== {path.relative_to(ROOT).as_posix()} =====",
                f'package.preload["{name}"] = function(...)',
                source,
                "end",
                "",
            )
        )

    sections.extend((ENTRY_MARKER, entry_point.rstrip(), ""))
    return "\n".join(sections), len(lua_files)


def long_bracket_level(source: str, start: int) -> int | None:
    """Return the equals-sign count for a Lua long bracket at start."""
    if start >= len(source) or source[start] != "[":
        return None
    cursor = start + 1
    while cursor < len(source) and source[cursor] == "=":
        cursor += 1
    if cursor < len(source) and source[cursor] == "[":
        return cursor - start - 1
    return None


def read_long_bracket(source: str, start: int, level: int) -> int:
    closing = "]" + ("=" * level) + "]"
    end = source.find(closing, start + level + 2)
    if end < 0:
        raise ValueError(f"Unterminated Lua long bracket at offset {start}")
    return end + len(closing)


def tokenize_lua(source: str) -> list[tuple[str, str]]:
    """Tokenize enough of Lua to safely remove comments and whitespace."""
    tokens: list[tuple[str, str]] = []
    cursor = 0
    length = len(source)

    while cursor < length:
        character = source[cursor]
        if character.isspace():
            cursor += 1
            continue

        if source.startswith("--", cursor):
            level = long_bracket_level(source, cursor + 2)
            if level is not None:
                cursor = read_long_bracket(source, cursor + 2, level)
            else:
                newline = source.find("\n", cursor + 2)
                cursor = length if newline < 0 else newline + 1
            continue

        if character in {'"', "'"}:
            quote = character
            end = cursor + 1
            while end < length:
                if source[end] == "\\":
                    end += 2
                elif source[end] == quote:
                    end += 1
                    break
                else:
                    end += 1
            else:
                raise ValueError(f"Unterminated Lua string at offset {cursor}")
            tokens.append(("string", source[cursor:end]))
            cursor = end
            continue

        level = long_bracket_level(source, cursor)
        if level is not None:
            end = read_long_bracket(source, cursor, level)
            tokens.append(("string", source[cursor:end]))
            cursor = end
            continue

        identifier = LUA_IDENTIFIER.match(source, cursor)
        if identifier:
            tokens.append(("word", identifier.group(0)))
            cursor = identifier.end()
            continue

        number = LUA_NUMBER.match(source, cursor)
        if number:
            tokens.append(("number", number.group(0)))
            cursor = number.end()
            continue

        operator = next(
            (value for value in LUA_OPERATORS if source.startswith(value, cursor)),
            character,
        )
        tokens.append(("symbol", operator))
        cursor += len(operator)

    return tokens


def tokens_need_separator(
    previous: tuple[str, str], current: tuple[str, str]
) -> bool:
    previous_kind, previous_text = previous
    current_kind, current_text = current
    if previous_kind in {"word", "number"} and current_kind in {"word", "number"}:
        return True
    if previous_kind == "number" and current_text.startswith("."):
        return True
    if previous_kind == "symbol" and current_kind == "symbol":
        return previous_text[-1] + current_text[0] in AMBIGUOUS_SYMBOL_BOUNDARIES
    return False


def minify_lua(source: str) -> str:
    """Remove Lua comments and unnecessary whitespace without renaming symbols."""
    tokens = tokenize_lua(source)
    if not tokens:
        return ""

    output = [tokens[0][1]]
    for previous, current in zip(tokens, tokens[1:]):
        if tokens_need_separator(previous, current):
            output.append(" ")
        output.append(current[1])
    return "".join(output)


def embed_version(bundle: str, version: str) -> str:
    marker = "__MATERIAL_OSC_VERSION__"
    if marker not in bundle:
        raise RuntimeError("Updater version marker was not found in the bundle")
    lua_version = version.replace("\\", "\\\\").replace('"', '\\"')
    return bundle.replace(marker, lua_version)


def subset_symbol_font(source_dir: Path, source_font: Path, output_font: Path) -> int:
    """Keep only Material Symbol ligatures referenced by the Lua sources."""
    try:
        from fontTools import subset
        from fontTools.ttLib import TTFont
    except ImportError as error:
        raise RuntimeError(
            "FontTools is required to build the icon subset. "
            "Install build dependencies with: pip install -r requirements-build.txt"
        ) from error

    font = TTFont(source_font)
    glyph_order = set(font.getGlyphOrder())
    candidates: set[str] = set()
    for lua_file in source_dir.rglob("*.lua"):
        candidates.update(LUA_STRING.findall(lua_file.read_text(encoding="utf-8")))
    icons = sorted(candidates & glyph_order)
    if not icons:
        raise RuntimeError("No Material Symbol icon names were found in the Lua sources")

    best_cmap = font.getBestCmap() or {}
    glyphs = set(icons)
    for icon in icons:
        for character in icon:
            glyph = best_cmap.get(ord(character))
            if glyph:
                glyphs.add(glyph)

    options = subset.Options()
    options.layout_features = ["rlig"]
    options.layout_closure = False
    options.glyph_names = True
    options.notdef_glyph = True
    options.notdef_outline = True
    options.recommended_glyphs = True
    options.name_IDs = ["*"]
    options.name_languages = ["*"]

    subsetter = subset.Subsetter(options=options)
    subsetter.populate(glyphs=glyphs)
    subsetter.subset(font)
    output_font.parent.mkdir(parents=True, exist_ok=True)
    font.save(output_font)
    return len(icons)


def optimize_text_font(source_font: Path, output_font: Path) -> tuple[int, int]:
    try:
        from fontTools.ttLib import TTFont
        from fontTools.varLib.instancer import instantiateVariableFont
    except ImportError as error:
        raise RuntimeError(
            "FontTools is required to optimize the text font. "
            "Install build dependencies with: pip install -r requirements-build.txt"
        ) from error

    font = TTFont(source_font)
    instantiateVariableFont(font, {
        "opsz": 18,
        "wdth": 100,
        "GRAD": 0,
        "ROND": 0,
        "slnt": 0,
    }, inplace=True, optimize=True)
    font.save(output_font)
    return source_font.stat().st_size, output_font.stat().st_size


def build_fonts(source_dir: Path, destination_fonts: Path) -> tuple[int, int, int, int, int]:
    if destination_fonts.exists():
        shutil.rmtree(destination_fonts)
    destination_fonts.mkdir(parents=True)

    source_symbol_font = FONTS_DIR / SYMBOL_FONT
    if not source_symbol_font.is_file():
        raise FileNotFoundError(f"Material Symbols source font not found: {source_symbol_font}")
    output_symbol_font = destination_fonts / OUTPUT_SYMBOL_FONT
    icon_count = subset_symbol_font(source_dir, source_symbol_font, output_symbol_font)

    source_text_font = FONTS_DIR / TEXT_FONT
    if not source_text_font.is_file():
        raise FileNotFoundError(f"Text font source not found: {source_text_font}")
    text_source_size, text_output_size = optimize_text_font(
        source_text_font, destination_fonts / OUTPUT_TEXT_FONT
    )
    return (
        icon_count,
        source_symbol_font.stat().st_size,
        output_symbol_font.stat().st_size,
        text_source_size,
        text_output_size,
    )


def validate_version(version: str) -> str:
    if not version or version in {".", ".."} or Path(version).name != version:
        raise argparse.ArgumentTypeError(
            "version must be a single non-empty directory name"
        )
    return version


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Create a versioned, deployable material-osc build."
    )
    parser.add_argument(
        "version", type=validate_version,
        help="version directory to create under build/ (for example, 1.2.0)",
    )
    parser.add_argument("--source-dir", type=Path, default=DEFAULT_SOURCE_DIR)
    args = parser.parse_args()

    source_dir = args.source_dir.resolve()
    destination = BUILD_DIR / args.version
    output = destination / "scripts" / "material-osc.lua"
    output.parent.mkdir(parents=True, exist_ok=True)

    bundle, module_count = build_bundle(source_dir, ENTRY_FILE)
    bundle = embed_version(bundle, args.version)
    unminified_size = len(bundle.encode("utf-8"))
    bundle = GENERATED_HEADER + "\n" + minify_lua(bundle)
    minified_size = len(bundle.encode("utf-8"))
    output.write_text(bundle, encoding="utf-8", newline="\n")

    legacy_script = destination / "material-osc.lua"
    if legacy_script.exists():
        legacy_script.unlink()
    legacy_fonts = destination / "material-osc"
    if legacy_fonts.exists():
        shutil.rmtree(legacy_fonts)
    (
        icon_count,
        source_font_size,
        subset_font_size,
        text_source_size,
        text_output_size,
    ) = build_fonts(source_dir, destination / "fonts")
    print(
        f"Built material-osc {args.version} with {module_count} modules and "
        f"{icon_count} icons in {destination}"
    )
    print(
        f"Minified material-osc.lua: {unminified_size // 1024} KiB -> "
        f"{minified_size // 1024} KiB"
    )
    print(
        f"Subset {SYMBOL_FONT}: {source_font_size // 1024} KiB -> "
        f"{subset_font_size // 1024} KiB"
    )
    print(
        f"Optimized {TEXT_FONT}: {text_source_size // 1024} KiB -> "
        f"{text_output_size // 1024} KiB"
    )


if __name__ == "__main__":
    main()
